#!/bin/bash

### BEGIN INIT INFO
# Provides:          irisv2
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop IRISv2 server
### END INIT INFO

IRIS_HOME=/opt/server

case $1 in
    start)
        echo $"Starting IRISv2 server ..."
        if [ ! -f /var/run/iris ]; then
            cd $IRIS_HOME
            nohup java -jar iris-core.jar 2>> /dev/null >> /dev/null &
            echo $! > /var/run/iris
            echo $"IRISv2 started ..."
        else
            echo $"IRISv2 is already running ..."
        fi
    ;;
    stop)
        if [ -f /var/run/iris ]; then
            PID=$(cat /var/run/iris);
            echo "Stopping IRISv2 server ..."
            kill $PID;
            echo "IRISv2 stopped ..."
            rm /var/run/iris
        else
            echo "IRISv2 is not running ..."
        fi
    ;;
    restart)
        stop
        start
    ;;
esac
